version: "3.8"

services:
  fronty-prod:
    build:
      context: ./
      dockerfile: Dockerfile
      target: prod
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production

  fronty:
    build:
      context: ./
      dockerfile: Dockerfile
      target: prod
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules

      # - NODE_ENV=dev
    command: ["/bin/sh", "-c", "yarn dev"]
    env_file:
      - .env
