import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/organisms/layout/Header";
import Footer from "@/components/organisms/layout/Footer";
const inter = Roboto({ weight: ['300', '400', '700', '900'], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className="mb-4">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
